### ISSUE TITLE
Badges for private respositories

### ISSUE THREAD

**Issue by ctaepper** [snyk/snyk#105]
From what I've read in the docs, badges for private repos are not supported. Can we somehow contribute to that? Shouldn't be more that some kind of hashkey added the to the url, authorizing public requests to the img/svg right?

**Comment by adrukh** [comment]
@ctaepper thanks for the suggestion!

We thought about implementing this, and your idea re hashkey on url is indeed the right way to do so. However, this is quite internal to our system and cannot be easily contributed to... Sorry and thanks again for suggesting this!

We'll update this issue when we have something to share, but right now I don't have a timeframe for this feature.

**Comment by ctaepper** [comment]
meanwhile, I implemented a custom solution using my snyk api token to access the (undocumented) snyk api via a self hosted bagde generator. For anyone having the same issue, this could be your starting point:

```ts
  // for convenience, save the organisation's id in env variables
  const apiUrl = `https://snyk.io/api/v1/org/${ENV.SNYK_ORG_ID}/projects`
  let svg
  try {
    // retrieve all projects
    const projects: Response = await request
      .get(apiUrl)
      .accept('application/json')
      .set('Authorization', ENV.SNYK_TOKEN)
    // filter the project you are looking for
    // my url looks like this https://shieldserver/snyk/orgname/reponame
    const project = projects.body.projects.find(
      p => p.name === repo.toLowerCase()
    )

    // get latest snyk snapshot of this repo
    const snapshot: Response = await request
      .get(`${apiUrl}/${project.id}`)
      .accept('application/json')
      .set('Authorization', ENV.SNYK_TOKEN)

    // test now contains the latest snyk test
    const test = snapshot.body.lastSnapshot

    // I now define my badge properties
    let color, value
    color = Colors.ok
    value = 0

    if (test.vulnsBySeverity.high > 0) {
      color = Colors.error
      value = test.vulnsBySeverity.high
    } else if (test.vulnsBySeverity.medium > 0) {
      color = Colors.warn
      value = test.vulnsBySeverity.medium
    } else if (test.vulnsBySeverity.low > 0) {
      color = Colors.info
      value = test.vulnsBySeverity.low
    }

    // and now use https://www.npmjs.com/package/gh-badges to actually create the badge
  } catch (err) {
    // do something with err
  }


```

**Comment by adrukh** [comment]
What a cool idea! :heart_eyes:

**Comment by samkit-jain** [comment]
Any update on this? Badges for private repos are still not supported.

**Comment by samkit-jain** [comment]
I wrote a simple Go app in case someone is interested. It is available at https://github.com/samkit-jain/snyk-badge
